### ISSUE TITLE
After trying to post, page goes blank.

### ISSUE THREAD

**Issue by HVNF** [cartpauj/mingle-forum#67]
Hello Paul,

When i want to post a question on our forum: https://www.hvnf.nl/vragen/?mingleforumaction=addtopic&forum=2.0
The page goes blank:
https://www.hvnf.nl/wp-content/plugins/mingle-forum/wpf-insert.php
Can you help us with this?

**Comment by cartpauj** [comment]
This is a totally dead project unfortunately, and has been for 4 or 5 years now. I would strongly consider migrating to bbPress or SimplePress forum. I think both have migrator scripts for Mingle Forum.

https://codex.bbpress.org/getting-started/importing-data/import-forums/mingle/

https://simple-press.com/downloads/simple-press-importer-plugin/

There's a free plugin that's very good also - though it doesn't have a migration script that I know of: https://wordpress.org/plugins/asgaros-forum/

**Comment by HVNF** [comment]
Thanks for the fast reply, Mingle forum was great. Thanks for advice on
migration.

Groet,

Jaap-Sip Faber
E-mail: info@jsfaber.nl

2017-10-06 21:19 GMT+02:00 Paul <notifications@github.com>:
